# -*- coding: utf-8 -*-
"""IBD_TP1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Zj4BFKqS4z3VPWTxYxX5PhH5mdiVjz_
"""

import duckdb

def query(queryStr):
  result = duckdb.query(queryStr).to_df()
  return result

def printQuery(queryStr):
  print(query(queryStr))

CLIENTES = 'clientes.csv'
FILMES = '/tables/filmes.csv'
INGRESSOS = 'tables/ingressos.csv'
SALAS = 'tables\salas.csv'
SESSOES = 'tables\sessoes.csv'

query_base = f"""
SELECT id, nome, email, data_nascimento
FROM {CLIENTES}
WHERE id > 90
--AND id < 95
"""

printQuery(query_base)

query_a1 = f"""
SELECT id, nome, email, data_nascimento
FROM {CLIENTES}
WHERE id > 90
--AND id < 95
"""

printQuery(query_a1)

query_a2 = f"""
SELECT id, nome, email, data_nascimento
FROM {CLIENTES}
WHERE id > 90
--AND id < 95
"""

printQuery(query_a2)

query_a3 = f"""
SELECT id, nome, email, data_nascimento
FROM {CLIENTES}
WHERE id > 90
--AND id < 95
"""

printQuery(query_a3)

query_a4 = f"""
SELECT id, nome, email, data_nascimento
FROM {CLIENTES}
WHERE id > 90
--AND id < 95
"""

printQuery(query_a4)

query_a5 = f"""
SELECT id, nome, email, data_nascimento
FROM {CLIENTES}
WHERE id > 90
--AND id < 95
"""

printQuery(query_a5)

query_a6 = f"""
SELECT id, nome, email, data_nascimento
FROM {CLIENTES}
WHERE id > 90
--AND id < 95
"""

printQuery(query_a6)

query_a7 = f"""
SELECT id, nome, email, data_nascimento
FROM {CLIENTES}
WHERE id > 90
--AND id < 95
"""

printQuery(query_a7)

query_a8 = f"""
SELECT id, nome, email, data_nascimento
FROM {CLIENTES}
WHERE id > 90
--AND id < 95
"""

printQuery(query_a8)

query_a9 = f"""
SELECT id, nome, email, data_nascimento
FROM {CLIENTES}
WHERE id > 90
--AND id < 95
"""

printQuery(query_a9)

query_a10 = f"""
SELECT id, nome, email, data_nascimento
FROM {CLIENTES}
WHERE id > 90
--AND id < 95
"""

printQuery(query_a10)